# Generated by Django 6.0.6 on 2026-06-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('data_ora', models.DateTimeField()),
                ('luogo', models.CharField(max_length=200)),
                ('capienza_massima', models.PositiveIntegerField()),
            ],
        ),
    ]
