# Generated by Django 6.0.6 on 2026-06-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_attendee',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_organizer',
            field=models.BooleanField(default=False, help_text="Indica se l'utente è un Organizzatore, se deselezionato è un mero partecipante."),
        ),
    ]
